### ISSUE TITLE
lib-version only without structopt dependency

### ISSUE THREAD

**Issue by dvtomas** [loony-bean/textplots-rs#36]
I'm using textplots as a lightweight lib only. Would it be possible to either split it into two crates, or use features, to have a `structopt` and `meval` dependencies free build?

**Comment by dvtomas** [comment]
Hello, anybody has an opinion on this?

**Comment by TDHolmes** [comment]
Makes sense to me. `structopt` and `meval` is only used in the binary CLI so I think it might be able to be moved to `[dev-dependencies]`. should be easy

**Comment by TDHolmes** [comment]
ah sorry, no it can't, but yeah it could be split into a feature and the CLI bin could be set to require that feature.

**Comment by dvtomas** [comment]
There's a discussion on how to do that in the "useful links" mentioned above.

**Comment by dvtomas** [comment]
/cc @micouy 

Any thoughts on this yet? IMHO it would be the best and easiest to just make the CLI another example. I'm willing to do a PR if you agree.

**Comment by dvtomas** [comment]
??

**Comment by TDHolmes** [comment]
I agree, I just hit this myself causing a duplicate dependency of a different version when I'm just using it as a library. I lean slightly towards the optional dependency or separate crate fix myself though.

**Comment by tobealive** [comment]
yep, would be great to have those options. Unfortunately, the crate becomes unusable in some cases until those things can be optionally enabled as features.

**Comment by adri326** [comment]
`meval` seems to be unmaintained, and it depends on `nom = ^1.0.0`, which will become rejected in a future version of rust (https://github.com/rust-lang/rust/issues/79813). The possible fixes for this upcoming deprecation are:

- backport the fix in `nom` to a `1.x.x` version (https://github.com/rust-bakery/nom/pull/1657). The fix is currently only live on versions `^5.1.3 || ^6.2.2 || >=7.0.0`
- convince the maintainer of `meval` to merge https://github.com/rekka/meval-rs/pull/27
- find an alternative to `meval` or fork it

**Comment by dvtomas** [comment]
I think this should go into another issue.

Anyway, If looking for an alternative, I've had a good experience with [evalexpr](https://crates.io/crates/evalexpr)

**Comment by loony-bean** [comment]
Fixed in #40
